development:
  strategy: oauth
  oauth_consumer_key: keys-removed-and-reset
  oauth_consumer_secret: keys-removed-and-reset
  base_url: "https://twitter.com"
  api_timeout: 10
  remember_for: 14 # days
  oauth_callback: "http://dearqut.local/oauth_callback"
  authorize_path: "/oauth/authenticate"
test: &TEST
  strategy: oauth
  oauth_consumer_key: 
  oauth_consumer_secret: 
  base_url: "https://twitter.com"
  api_timeout: 10
  remember_for: 14 # days
  oauth_callback: "http://dearqut.local/oauth_callback"
  authorize_path: "/oauth/authenticate"
cucumber:
  <<: *TEST
production:
  strategy: oauth
  oauth_consumer_key: keys-removed-and-reset
  oauth_consumer_secret: keys-removed-and-reset
  base_url: "https://twitter.com"
  api_timeout: 10
  remember_for: 14 # days
  oauth_callback: "http://dearqut.com/oauth_callback"
  authorize_path: "/oauth/authenticate"
